package entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import entity.Set;

import entity.SetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig setDaoConfig;

    private final SetDao setDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        setDaoConfig = daoConfigMap.get(SetDao.class).clone();
        setDaoConfig.initIdentityScope(type);

        setDao = new SetDao(setDaoConfig, this);

        registerDao(Set.class, setDao);
    }
    
    public void clear() {
        setDaoConfig.getIdentityScope().clear();
    }

    public SetDao getSetDao() {
        return setDao;
    }

}
