package com.invengo.resource.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SET.
 */
public class Set {

    private Long id;
    private String set_name;
    private String set_image_name;
    private Boolean set_sys_show;
    private Boolean set_set_show;

    public Set() {
    }

    public Set(Long id) {
        this.id = id;
    }

    public Set(Long id, String set_name, String set_image_name, Boolean set_sys_show, Boolean set_set_show) {
        this.id = id;
        this.set_name = set_name;
        this.set_image_name = set_image_name;
        this.set_sys_show = set_sys_show;
        this.set_set_show = set_set_show;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSet_name() {
        return set_name;
    }

    public void setSet_name(String set_name) {
        this.set_name = set_name;
    }

    public String getSet_image_name() {
        return set_image_name;
    }

    public void setSet_image_name(String set_image_name) {
        this.set_image_name = set_image_name;
    }

    public Boolean getSet_sys_show() {
        return set_sys_show;
    }

    public void setSet_sys_show(Boolean set_sys_show) {
        this.set_sys_show = set_sys_show;
    }

    public Boolean getSet_set_show() {
        return set_set_show;
    }

    public void setSet_set_show(Boolean set_set_show) {
        this.set_set_show = set_set_show;
    }

}
